global:
  address: ":53"
  allowTransfer:
    - "1.2.3.4"
    - "::1"
  defaultProvider: opendns

providers:
  - name: cf
    ip:
      - 1.1.1.1:53
      - 1.0.0.1:53
  - name: google
    ip:
      - 8.8.8.8:53
      - 4.2.2.4:53
  - name: opendns
    ip:
      - 208.67.222.123:53
      - 208.67.220.123:53
  - name: shecan
    ip:
      - 178.22.122.100:53
      - 185.51.200.2:53
  - name: "403"
    ip:
      - 10.202.10.202:53
      - 10.202.10.102:53
  - name: "radar-game"
    ip:
      - 10.202.10.11:53
      - 10.202.10.10:53

rules:
  - name: Ea blaze (Direct)
    matcher: regex
    matcherParams:
      - (.*\.)?blaze\.ea\.com
    resolver: opendns

  - name: Ea proxy
    matcher: regex
    matcherParams:
      - (.*\.)?ea\..*
      - (.*\.)?origin\..*
      - (.*\.)?tnt-ea\..*
      - (.*\.)?eac-cdn\..*
    resolver: "radar-game"

  - name: EasyAntiCheat proxy
    matcher: regex
    matcherParams:
      - (.*\.)?easyanticheat.net\..*
    resolver: "radar-game"

  - name: golang proxy
    matcher: regex
    matcherParams:
      - (.*\.)?golang\..*
      - (.*\.)?go-mpulse.net
    resolver: shecan
  - name: Amazon proxy
    matcher: regex
    matcherParams:
      - (.*\.)amazonaws.com
    resolver: "radar-game"

  - name: GlobalConfigs proxy
    matcher: regex
    matcherParams:
      - (.*\.)?googleapis\..*
      - (.*\.)?googlehosted.com
      - (.*\.)?bard.google.com
    resolver: "shecan"
  - name: 403 fallback
    matcher: regex
    matcherParams:
      - (.*)?\.403
    resolver: "403"

  - name: Spotify proxy
    matcher: regex
    matcherParams:
      - (.*\.)?spotify\..*
      - (.*\.)?akamaihd\..*
      - (.*\.)?scdn\..*
      - (.*\.)?spotifycdn\..*
    resolver: shecan

  - name: Sentry proxy
    matcher: regex
    matcherParams:
      - (.*\.)?sentry\..*
    resolver: shecan

  - name: Flutter-Pub proxy
    matcher: regex
    matcherParams:
      - (.*\.)?flutter.*
      - (.*\.)?pub.dev.*
    resolver: "shecan"

  - name: DartLang proxy
    matcher: regex
    matcherParams:
      - (.*\.)?dartlang.*
    resolver: "shecan"

  - name: Raw proxy
    matcher: exact
    matcherParams:
      - raw.raw.
    raw:
      A: raw.raw.	60	IN	A	1.2.3.4
      AAAA: raw.raw. 60 IN AAAA FFFF:FFFF:FFFF:FFFF::FFFF
