global:
  address: ":53"
  allowTransfer:
    - "0.0.0.0"
    - "127.0.0.1"
    - "::1"
  defaultProviders: opendns

providers:
  - name: cf
    ip:
      - 1.1.1.1:53
      - 1.0.0.1:53
  - name: google
    ip:
      - 8.8.8.8:53
      - 4.2.2.4:53
  - name: opendns
    ip:
      - 208.67.222.123:53
      - 208.67.220.123:53
  - name: shecan
    ip:
      - 178.22.122.100:53
      - 185.51.200.2:53
  - name: "403"
    ip:
      - 10.202.10.202:53
      - 10.202.10.102:53
  - name: "radar-game"
    ip:
      - 10.202.10.11:53
      - 10.202.10.10:53
  - name: "FAILED"
    ip:
      - 1.2.3.4:5
      - 6.7.8.9:10

rules:
  # - name: MultiResolver Test
  #   matcher: regex
  #   matcherParams:
  #     - (.*)
  #   resolvers:
  #     - FAILED
  #     - opendns
  - name: Ea blaze (Direct)
    matcher: regex
    matcherParams:
      - (.*\.)?blaze\.ea\.com
      - (.*\.)?spring18\.gosredirector\.ea\.com
      # - (.*\.)?juno\.ea\.com
    resolvers: opendns

  - name: Ea Acc proxy
    matcher: regex
    matcherParams:
      - (.*\.)?accounts\.ea\.com.*
      - (.*\.)?signin\.ea.com\.*
      - (.*\.)?ea\..*
      - (.*\.)?origin\..*
      - (.*\.)?tnt-ea\..*
      - (.*\.)?eac-cdn\..*
      - (.*\.)?eac-cdn\..*
      - (.*\.)?azure\..*
      - (.*\.)?dice\.se
      - (.*\.)?azurefd\.net
      - (.*\.)?footprintdns\..*
      - (.*\.)?sentry\.io
    resolvers: "shecan"
    resolverParams: ea.com.

  - name: EasyAntiCheat proxy
    matcher: regex
    matcherParams:
      - (.*\.)?easyanticheat.net\..*
    resolvers: "shecan"

  - name: golang proxy
    matcher: regex
    matcherParams:
      - (.*\.)?golang\..*
      - (.*\.)?go-mpulse.net
    resolvers: shecan
  - name: Amazon proxy
    matcher: regex
    matcherParams:
      - (.*\.)amazonaws.com
    resolvers: "shecan"
    # resolverParams: ea.com.

  - name: Bard proxy
    matcher: regex
    matcherParams:
      - (.*\.)?bard\.google\.com
    resolvers: "shecan"
    resolverParams: ea.com.

  - name: GlobalConfigs proxy
    matcher: regex
    matcherParams:
      - (.*\.)?googleapis\..*
      - (.*\.)?googlehosted.com
    resolvers: "shecan"
    resolverParams: ea.com.

  - name: 403 fallback
    matcher: regex
    matcherParams:
      - (.*)?\.403
    resolvers: "403"

  - name: Spotify proxy
    matcher: regex
    matcherParams:
      - (.*\.)?spotify\..*
      - (.*\.)?akamaihd\..*
      - (.*\.)?scdn\..*
      - (.*\.)?spotifycdn.com
    resolvers: shecan
    resolverParams: ea.com.

  - name: Sentry proxy
    matcher: regex
    matcherParams:
      - (.*\.)?sentry\..*
    resolvers: shecan

  - name: Flutter-Pub proxy
    matcher: regex
    matcherParams:
      - (.*\.)?flutter.*
      - (.*\.)?pub.dev.*
    resolvers: "shecan"

  - name: DartLang proxy
    matcher: regex
    matcherParams:
      - (.*\.)?dartlang.*
    resolvers: "shecan"
