global:
  address: ":53"
  allowTransfer:
    - "0.0.0.0"
    - "127.0.0.1"
    - "::1"
  defaultProviders: opendns

providers:
  - name: cf
    ip:
      - 1.1.1.1:53
      - 1.0.0.1:53
  - name: google
    ip:
      - 8.8.8.8:53
      - 4.2.2.4:53
  - name: opendns
    ip:
      - 208.67.222.123:53
      - 208.67.220.123:53
  - name: shecan
    ip:
      - 178.22.122.100:53
      - 185.51.200.2:53
  - name: "403"
    ip:
      - 10.202.10.202:53
      - 10.202.10.102:53
  - name: "radar-game"
    ip:
      - 10.202.10.11:53
      - 10.202.10.10:53

rules:
  - name: Ea blaze (Direct)
    matcher: regex
    matcherParams:
      - (.*\.)?blaze\.ea\.com
    resolvers: opendns

  - name: Ea Acc proxy
    matcher: regex
    matcherParams:
      - (.*\.)?accounts\.ea\.com.*
      - (.*\.)?signin\.ea.com\.*
    resolvers: "shecan"
    resolverParams: ea.com.
  #    raw:
  #      A: "{{ .address }}	60	IN	A	50.7.87.85"

  - name: Ea proxy
    matcher: regex
    matcherParams:
      - (.*\.)?ea\..*
      - (.*\.)?origin\..*
      - (.*\.)?tnt-ea\..*
      - (.*\.)?eac-cdn\..*
      - (.*\.)?eac-cdn\..*
      - (.*\.)?azure\..*
      - (.*\.)?footprintdns\..*
    resolvers: "shecan"

  - name: EasyAntiCheat proxy
    matcher: regex
    matcherParams:
      - (.*\.)?easyanticheat.net\..*
    resolvers: "shecan"

  - name: golang proxy
    matcher: regex
    matcherParams:
      - (.*\.)?golang\..*
      - (.*\.)?go-mpulse.net
    resolvers: shecan
  - name: Amazon proxy
    matcher: regex
    matcherParams:
      - (.*\.)amazonaws.com
    resolvers: "shecan"

  - name: GlobalConfigs proxy
    matcher: regex
    matcherParams:
      - (.*\.)?googleapis\..*
      - (.*\.)?googlehosted.com
      - (.*\.)?bard.google.com
    resolvers: "shecan"
  - name: 403 fallback
    matcher: regex
    matcherParams:
      - (.*)?\.403
    resolvers: "403"

  - name: Spotify proxy
    matcher: regex
    matcherParams:
      - (.*\.)?spotify\..*
      - (.*\.)?akamaihd\..*
      - (.*\.)?scdn\..*
      - (.*\.)?spotifycdn\..*
    resolvers: shecan

  - name: Sentry proxy
    matcher: regex
    matcherParams:
      - (.*\.)?sentry\..*
    resolvers: shecan

  - name: Flutter-Pub proxy
    matcher: regex
    matcherParams:
      - (.*\.)?flutter.*
      - (.*\.)?pub.dev.*
    resolvers: "shecan"

  - name: DartLang proxy
    matcher: regex
    matcherParams:
      - (.*\.)?dartlang.*
    resolvers: "shecan"

  - name: Raw proxy
    matcher: exact
    matcherParams:
      - raw.raw.
    raw:
      A: "{{ .address }} 60	IN	A	1.2.3.4"
      AAAA: "{{ .address }} 60 IN AAAA FFFF:FFFF:FFFF:FFFF::FFFF"

  - name: Bard proxy
    matcher: regex
    matcherParams:
      - (.*\.)?bard\.google\.com
    resolvers: "shecan"
    resolverParams: ea.com.

  - name: Test
    matcher: regex
    matcherParams:
      - (.*\.)?test.domain.com
    raw:
      A: |
        test.domain.com 60 IN CNAME	google.403.
        google.403.		60	IN	A	127.0.0.1
