apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockery-lts
  labels:
    app: mockery-lts
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mockery-lts
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: "600"
  template:
    metadata:
      labels:
        app: mockery-lts
        name: mockery-lts
    spec:
      containers:
        - name: mockery-lts
          image: fmotalleb/mockery:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          resources:
            limits: &a1
              cpu: "0.1"
              ephemeral-storage: 0.1G
              memory: 0.1G
            requests: *a1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: data-z14c11d2
              mountPath: /root/
          env:
            - name: CONFIG_FILE
              value: /root/config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: data-z14c11d2
          secret:
            secretName: data-z14c11d2
---
kind: Secret
apiVersion: v1
metadata:
  name: data-z14c11d2
stringData:
  config.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mockerylts
      labels:
        app: mockerylts
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          app: mockerylts
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: "600"
      template:
        metadata:
          labels:
            app: mockerylts
            name: mockerylts
        spec:
          containers:
            - name: mockerylts
              image: fmotalleb/mockery:latest
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 80
                  protocol: TCP
                  name: http
              resources:
                limits:
                  &a1
                  cpu: "0.1"
                  ephemeral-storage: 0.1G
                  memory: 0.1G
                requests: *a1
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - name: data-onjlhlz8
                  mountPath: /root/
              env:
                - name: mockerylts
                  value: null
                - name: CONFIG_FILE
                  value: /root/config.yaml
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: data-onjlhlz8
              secret:
                secretName: data-onjlhlz8
    ---
    kind: Secret
    apiVersion: v1
    metadata:
      name: data-onjlhlz8
    stringData:
      config.yaml: |
        global:
          address: ":53"
          allowTransfer:
            - "1.2.3.4"
            - "::1"
          defaultProvider: opendns

        providers:
          - name: cf
            ip:
              - 1.1.1.1:53
              - 1.0.0.1:53
          - name: google
            ip:
              - 8.8.8.8:53
              - 4.2.2.4:53
          - name: opendns
            ip:
              - 208.67.222.123:53
              - 208.67.220.123:53
          - name: shecan
            ip:
              - 178.22.122.100:53
              - 185.51.200.2:53
          - name: "403"
            ip:
              - 10.202.10.202:53
              - 10.202.10.102:53

        rules:
          - name: Ea blaze (Direct)
            matcher: regex
            matcherParams:
              - .*blaze\.ea\.com
            resolver: opendns
          - name: Ea proxy
            matcher: regex
            matcherParams:
              - .*\.ea\..*
              - ea\..*
              - .*\.origin\..*
              - origin\..*
              - .*\.tnt-ea\..*
              - tnt-ea\..*
            resolver: shecan
          - name: Spotify proxy
            matcher: regex
            matcherParams:
              - .*\.spotify\..*
              - spotify\..*
              - .*\.akamaihd\..*
              - akamaihd\..*
              - .*\.scdn\..*
              - scdn\..*
              - .*\.spotifycdn\..*
              - spotifycdn\..*
            resolver: shecan
          - name: Sentry proxy
            matcher: regex
            matcherParams:
              - .*\.sentry\..*
              - sentry\..*
            resolver: shecan
    ---
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: mockerylts-free-sub
    spec:
      host: mockerylts-temop.apps.ir-thr-ba1.arvanpaas.ir
      port:
        targetPort: http
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: mockerylts
        weight: 100
      wildcardPolicy: None
    ---
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: mockerylts
      name: mockerylts
    spec:
      ports:
        - name: http
          protocol: TCP
          targetPort: http
          port: 80
      selector:
        app: mockerylts
      type: ClusterIP
