apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockery
  labels:
    app: mockery
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mockery
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: "600"
  template:
    metadata:
      labels:
        app: mockery
        name: mockery
    spec:
      containers:
        - name: mockery
          image: fmotalleb/mockery:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          resources:
            limits: &a1
              cpu: "0.1"
              ephemeral-storage: 0.1G
              memory: 0.1G
            requests: *a1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: data-vo5umog2
              mountPath: /root/
          env:
            - name: mokcery
              value: null
            - name: LOG_LEVEL
              value: debug
            - name: CONFIG_FILE
              value: /root/config.yaml
            - name: WATCH_CONFIG_FILE
              value: "false"
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: LOG_FILE
              value: /dns.log
          command:
            - dns
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: data-vo5umog2
          secret:
            secretName: data-vo5umog2
---
kind: Secret
apiVersion: v1
metadata:
  name: data-vo5umog2
stringData:
  config.yaml: |
    global:
      address: ":53"
      allowTransfer:
        - "1.2.3.4"
        - "::1"
      defaultProvider: opendns

    providers:
      - name: cf
        ip:
          - 1.1.1.1:53
          - 1.0.0.1:53
      - name: google
        ip:
          - 8.8.8.8:53
          - 4.2.2.4:53
      - name: opendns
        ip:
          - 208.67.222.123:53
          - 208.67.220.123:53
      - name: shecan
        ip:
          - 178.22.122.100:53
          - 185.51.200.2:53
      - name: "403"
        ip:
          - 10.202.10.202:53
          - 10.202.10.102:53

    rules:
      - name: Ea blaze (Direct)
        matcher: regex
        matcherParams:
          - .*blaze\.ea\.com
        resolver: opendns
      - name: Ea proxy
        matcher: regex
        matcherParams:
          - .*\.ea\..*
          - ea\..*
          - .*\.origin\..*
          - origin\..*
          - .*\.tnt-ea\..*
          - tnt-ea\..*
        resolver: shecan
      - name: Spotify proxy
        matcher: regex
        matcherParams:
          - .*\.spotify\..*
          - spotify\..*
          - .*\.akamaihd\..*
          - akamaihd\..*
          - .*\.scdn\..*
          - scdn\..*
          - .*\.spotifycdn\..*
          - spotifycdn\..*
        resolver: shecan
      - name: Sentry proxy
        matcher: regex
        matcherParams:
          - .*\.sentry\..*
          - sentry\..*
        resolver: shecan
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mockery-free-sub
spec:
  host: mockery-temop.apps.ir-thr-ba1.arvanpaas.ir
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mockery
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mockery
  name: mockery
spec:
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 80
    - name: uud5nsqq
      protocol: UDP
      targetPort: 53
      port: 53
  selector:
    app: mockery
  type: ClusterIP
