name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"
          check-latest: true
      - name: install deps
        run: |
          go install golang.org/x/lint/golint@latest
      - run: go build -v ./...
      - run: go test -v ./...
      - run: go vet ./...
      - run: golint -set_exit_status ./...
